apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ci

#
# Kustomize will add the namespace and labels to all files being kustomized
#
commonLabels:
  pipeline: tekton
  deploy: argocd

resources:
  - tasks/buildpack-task.yaml
  - tasks/argocd-deploy-task.yaml
  - tasks/kustomize-task.yaml
  - tasks/slack-notification-task.yaml  
  - tasks/kaniko-task.yaml
  - triggers/github-trigger-binding.yaml