
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: wordpress-build-pipeline-trigger-template
spec:
  params:
    - name: application
    - name: project
    - name: sha
    - name: head_commit
    - name: head_commit_message
    - name: pusher_name
    - name: pusher_email
    - name: pusher_avatar
    - name: pusher_url
    - name: repository_url
    - name: repository_ssh_url
    - name: environment
    - name: branch
    - name: kubernetes_namespace

  resourcetemplates:
  - kind: PipelineRun
    apiVersion: tekton.dev/v1beta1
    metadata:
      generateName: $(tt.params.application)-build-pipeline-run-
    spec:
      serviceAccountName: $(tt.params.application)-build-pipeline-sa
      pipelineRef:
        name: wordpress-build-pipeline
      params:
        - name: "application"
          value: "$(tt.params.application)"
        - name: "project"
          value: "$(tt.params.project)"
        - name: sha
          value: "$(tt.params.sha)"
        - name: head_commit
          value: "$(tt.params.head_commit)"
        - name: head_commit_message
          value: "$(tt.params.head_commit_message)"
        - name: pusher_name
          value: "$(tt.params.pusher_name)"
        - name: pusher_email
          value: "$(tt.params.pusher_email)"
        - name: pusher_avatar
          value: "$(tt.params.pusher_avatar)"
        - name: pusher_url
          value: "$(tt.params.pusher_url)"
        - name: repository_url
          value: "$(tt.params.repository_url)"
        - name: repository_ssh_url
          value: "$(tt.params.repository_ssh_url)"
        - name: environment
          value: "$(tt.params.environment)"
        - name: branch
          value: "$(tt.params.branch)"
        - name: kubernetes_namespace
          value: "$(tt.params.kubernetes_namespace)"

      podTemplate:
        volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        nodeSelector:
          ci: "true"
        tolerations:
          - key: "ci"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
