apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ci

#
# Kustomize will add the namespace and labels to all files being kustomized
#
commonLabels:
  pipeline: buildpacks
  deploy: argocd

resources:
  - triggers/build-pipeline-trigger.yaml
  - build-pipeline.yaml